/-
Copyright (c) 2026 Junye Ji. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Junye Ji
-/
module

public import NormalForms.Applications.RationalCanonical.Result
import NormalForms.Matrix.Smith.Data
import Mathlib.LinearAlgebra.AnnihilatingPolynomial

/-!
# The Largest Invariant Factor and the Minimal Polynomial

For a nonzero-dimensional rational endomorphism, the annihilator of its
`Module.AEval'` module is the ideal generated by the minimal polynomial.  The
certified cyclic Smith decomposition identifies the same annihilator with the
intersection of the invariant-factor ideals.  The Smith divisibility chain
makes that intersection the ideal generated by the final factor.

Both generators are monic, so the executable final factor equals mathlib's
minimal polynomial exactly, not merely up to association.
-/

namespace NormalForms.RationalCanonical

open Polynomial
open NormalForms.Matrix.Smith

private theorem invariantFactor_dvd_last
    {k : Nat}
    (A : Matrix (Fin (k + 1)) (Fin (k + 1)) Rat)
    (i : Fin (k + 1)) :
    endomorphismInvariantFactor A i ∣
      endomorphismInvariantFactor A (Fin.last k) := by
  let result := endomorphismSmithResult A
  let data := result.smithData
  let castIndex : Fin (k + 1) → Fin (Nat.min (k + 1) (k + 1)) :=
    Fin.cast (by simp)
  have hdiv :=
    data.divisibility
      (castIndex i)
      (castIndex (Fin.last k))
      (by
        simp only [castIndex, Fin.val_cast, Fin.val_last]
        exact Nat.le_of_lt_succ i.isLt)
  have hi :
      Fin.castLE (Nat.min_le_left (k + 1) (k + 1))
          (castIndex i) =
        i := by
    apply Fin.ext
    rfl
  have hlast :
      Fin.castLE (Nat.min_le_left (k + 1) (k + 1))
          (castIndex (Fin.last k)) =
        Fin.last k := by
    apply Fin.ext
    rfl
  dsimp only [data, result] at hdiv
  rw [SNFResultFin.smithData_diagonal,
    SNFResultFin.smithData_diagonal] at hdiv
  change
    (endomorphismSmithResult A).S
          (Fin.castLE (Nat.min_le_left (k + 1) (k + 1))
            (castIndex i))
          (Fin.castLE (Nat.min_le_right (k + 1) (k + 1))
            (castIndex i)) ∣
      (endomorphismSmithResult A).S
          (Fin.castLE (Nat.min_le_left (k + 1) (k + 1))
            (castIndex (Fin.last k)))
          (Fin.castLE (Nat.min_le_right (k + 1) (k + 1))
            (castIndex (Fin.last k))) at hdiv
  rw [hi, hlast,
    endomorphismSmithResult_diagonal,
    endomorphismSmithResult_diagonal] at hdiv
  exact hdiv

private theorem invariantFactorIdeal_iInf_eq_last
    {k : Nat}
    (A : Matrix (Fin (k + 1)) (Fin (k + 1)) Rat) :
    (⨅ i : Fin (k + 1),
        Ideal.span
          ({endomorphismInvariantFactor A i} : Set Rat[X])) =
      Ideal.span
        ({endomorphismInvariantFactor A (Fin.last k)} :
          Set Rat[X]) := by
  apply le_antisymm
  · exact iInf_le _ (Fin.last k)
  · refine le_iInf fun i => ?_
    rw [Ideal.span_singleton_le_span_singleton]
    exact invariantFactor_dvd_last A i

private theorem span_minpoly_eq_lastInvariantFactor
    {k : Nat}
    (A : Matrix (Fin (k + 1)) (Fin (k + 1)) Rat) :
    Ideal.span ({minpoly Rat A} : Set Rat[X]) =
      Ideal.span
        ({endomorphismInvariantFactor A (Fin.last k)} :
          Set Rat[X]) := by
  calc
    Ideal.span ({minpoly Rat A} : Set Rat[X]) =
        Ideal.span
          ({minpoly Rat A.toLin'} : Set Rat[X]) := by
      rw [Matrix.minpoly_toLin']
    _ =
        Module.annihilator Rat[X]
          (EndomorphismModule A) :=
      Polynomial.span_minpoly_eq_annihilator Rat A.toLin'
    _ =
        Module.annihilator Rat[X]
          ((i : Fin (k + 1)) →
            Rat[X] ⧸
              Ideal.span
                ({endomorphismInvariantFactor A i} :
                  Set Rat[X])) :=
      (endomorphismCyclicDecomposition A).annihilator_eq
    _ =
        ⨅ i : Fin (k + 1),
          Module.annihilator Rat[X]
            (Rat[X] ⧸
              Ideal.span
                ({endomorphismInvariantFactor A i} :
                  Set Rat[X])) :=
      Module.annihilator_pi
    _ =
        ⨅ i : Fin (k + 1),
          Ideal.span
            ({endomorphismInvariantFactor A i} :
              Set Rat[X]) := by
      congr 1
      funext i
      exact Ideal.annihilator_quotient
    _ =
        Ideal.span
          ({endomorphismInvariantFactor A (Fin.last k)} :
            Set Rat[X]) :=
      invariantFactorIdeal_iInf_eq_last A

public theorem lastInvariantFactor_eq_minpoly
    {k : Nat}
    (A : Matrix (Fin (k + 1)) (Fin (k + 1)) Rat) :
    endomorphismInvariantFactor A (Fin.last k) =
      minpoly Rat A := by
  apply Polynomial.eq_of_monic_of_associated
    (endomorphismInvariantFactor_monic A (Fin.last k))
    (minpoly.monic (Matrix.isIntegral A))
  exact Ideal.span_singleton_eq_span_singleton.mp
    (span_minpoly_eq_lastInvariantFactor A).symm

public theorem largestInvariantFactor?_eq_minpoly
    {n : Nat}
    (A : Matrix (Fin n) (Fin n) Rat)
    (hn : 0 < n) :
    largestInvariantFactor? A =
      some (minpoly Rat A) := by
  cases n with
  | zero => omega
  | succ k =>
      rw [largestInvariantFactor?_succ,
        lastInvariantFactor_eq_minpoly]

end NormalForms.RationalCanonical
