/-
Copyright (c) 2026 Junye Ji. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Junye Ji
-/
module

public import NormalForms.Bridge.MathlibPID

/-!
# Finite Free Presentations

The stable column-oriented presentation interface.  A matrix with
`numGenerators` rows and `numRelations` columns denotes the relation map

`R^numRelations → R^numGenerators`.

The presented module is its cokernel.  Smith decomposition retains every
nonzero invariant factor, including units; `displayInvariantFactors` is the
separate reader that removes unit factors for human-facing output.
-/

@[expose] public section

namespace NormalForms

open Bridge.MathlibPID
open Matrix.Smith

/--
A finite presentation between finite free modules.

Columns are relations and rows are generators.
-/
public structure FiniteFreePresentation (R : Type u) where
  numGenerators : Nat
  numRelations : Nat
  relationMatrix :
    _root_.Matrix (Fin numGenerators) (Fin numRelations) R

namespace FiniteFreePresentation

/-- The free module on the presentation generators. -/
public abbrev generatorModule
    {R : Type _} [CommRing R]
    (presentation : FiniteFreePresentation R) :=
  Fin presentation.numGenerators → R

/-- The free module on the presentation relations. -/
public abbrev relationModule
    {R : Type _} [CommRing R]
    (presentation : FiniteFreePresentation R) :=
  Fin presentation.numRelations → R

/--
The relation map.  Its domain is indexed by columns and its codomain by rows.
-/
public def relationMap
    {R : Type _} [CommRing R]
    (presentation : FiniteFreePresentation R) :
    presentation.relationModule →ₗ[R] presentation.generatorModule :=
  presentation.relationMatrix.mulVecLin

/-- The submodule generated by the relation columns. -/
public abbrev relationSubmodule
    {R : Type _} [CommRing R]
    (presentation : FiniteFreePresentation R) :
    Submodule R presentation.generatorModule :=
  LinearMap.range presentation.relationMap

/-- The cokernel of the column-oriented relation map. -/
public abbrev presentedModule
    {R : Type _} [CommRing R]
    (presentation : FiniteFreePresentation R) :=
  presentation.generatorModule ⧸ presentation.relationSubmodule

/-- The stable arbitrary-index Smith result used by the quotient decomposition. -/
public noncomputable def smithResult
    {R : Type _}
    [EuclideanDomain R] [NormalizationMonoid R]
    [ComputableEuclideanOps R] [DecidableEq R]
    [Matrix.Hermite.CanonicalMod R]
    (presentation : FiniteFreePresentation R) :
    SNFResult presentation.relationMatrix :=
  smithNormalForm presentation.relationMatrix

/-- Intrinsic ordered Smith data for the relation matrix. -/
public noncomputable def smithData
    {R : Type _}
    [EuclideanDomain R] [NormalizationMonoid R]
    [ComputableEuclideanOps R] [DecidableEq R]
    [Matrix.Hermite.CanonicalMod R]
    (presentation : FiniteFreePresentation R) :
    SmithData presentation.numGenerators presentation.numRelations R := by
  let source := presentation.smithResult.smithData
  let hdim :
      Nat.min presentation.numGenerators presentation.numRelations =
        Nat.min (Fintype.card (Fin presentation.numGenerators))
          (Fintype.card (Fin presentation.numRelations)) := by
    simp
  exact
    { rank := source.rank
      rank_le := by
        simpa using source.rank_le
      diagonal := fun i => source.diagonal (Fin.cast hdim i)
      nonzero_prefix := by
        intro i hi
        exact source.nonzero_prefix (Fin.cast hdim i) (by simpa using hi)
      zero_tail := by
        intro i hi
        exact source.zero_tail (Fin.cast hdim i) (by simpa using hi)
      normalized := by
        intro i
        exact source.normalized (Fin.cast hdim i)
      divisibility := by
        intro i j hij
        exact source.divisibility (Fin.cast hdim i) (Fin.cast hdim j)
          (by simpa using hij) }

/-- Intrinsic Smith signature of the presentation. -/
public noncomputable def smithSignature
    {R : Type _}
    [EuclideanDomain R] [NormalizationMonoid R]
    [ComputableEuclideanOps R] [DecidableEq R]
    [Matrix.Hermite.CanonicalMod R]
    (presentation : FiniteFreePresentation R) :
    SmithSignature R :=
  presentation.smithData.signature

/-- Exact number of nonzero Smith factors, including unit factors. -/
public noncomputable abbrev smithRank
    {R : Type _}
    [EuclideanDomain R] [NormalizationMonoid R]
    [ComputableEuclideanOps R] [DecidableEq R]
    [Matrix.Hermite.CanonicalMod R]
    (presentation : FiniteFreePresentation R) : Nat :=
  pidExecutableInvariantFactorCount presentation.relationMatrix

/-- The `i`th normalized nonzero Smith factor, including units. -/
public noncomputable abbrev invariantFactor
    {R : Type _}
    [EuclideanDomain R] [NormalizationMonoid R]
    [ComputableEuclideanOps R] [DecidableEq R]
    [Matrix.Hermite.CanonicalMod R]
    (presentation : FiniteFreePresentation R) :
    Fin presentation.smithRank → R :=
  pidExecutableInvariantFactorFn presentation.relationMatrix

/-- The ordered normalized nonzero Smith factors, including units. -/
public noncomputable abbrev invariantFactors
    {R : Type _}
    [EuclideanDomain R] [NormalizationMonoid R]
    [ComputableEuclideanOps R] [DecidableEq R]
    [Matrix.Hermite.CanonicalMod R]
    (presentation : FiniteFreePresentation R) : List R :=
  pidSmithNormalFormCoeffList presentation.relationMatrix

/-- Rank of the free summand in the presented cokernel. -/
public noncomputable abbrev freeRank
    {R : Type _}
    [EuclideanDomain R] [NormalizationMonoid R]
    [ComputableEuclideanOps R] [DecidableEq R]
    [Matrix.Hermite.CanonicalMod R]
    (presentation : FiniteFreePresentation R) : Nat :=
  Fintype.card (Fin presentation.numGenerators) - presentation.smithRank

@[simp] public theorem freeRank_eq
    {R : Type _}
    [EuclideanDomain R] [NormalizationMonoid R]
    [ComputableEuclideanOps R] [DecidableEq R]
    [Matrix.Hermite.CanonicalMod R]
    (presentation : FiniteFreePresentation R) :
    presentation.freeRank =
      presentation.numGenerators - presentation.smithRank := by
  rw [freeRank, Fintype.card_fin]

@[simp] public theorem smithData_rank
    {R : Type _}
    [EuclideanDomain R] [NormalizationMonoid R]
    [ComputableEuclideanOps R] [DecidableEq R]
    [Matrix.Hermite.CanonicalMod R]
    (presentation : FiniteFreePresentation R) :
    presentation.smithData.rank = presentation.smithRank := by
  calc
    presentation.smithData.rank =
        presentation.smithResult.invariantFactors.length :=
      presentation.smithResult.smithData_rank
    _ = (pidSmithNormalFormCoeffList presentation.relationMatrix).length := rfl
    _ = presentation.smithRank :=
      (pidExecutableInvariantFactorCount_eq_length
        presentation.relationMatrix).symm

@[simp] public theorem invariantFactors_length
    {R : Type _}
    [EuclideanDomain R] [NormalizationMonoid R]
    [ComputableEuclideanOps R] [DecidableEq R]
    [Matrix.Hermite.CanonicalMod R]
    (presentation : FiniteFreePresentation R) :
    presentation.invariantFactors.length = presentation.smithRank := by
  rfl

/--
Filter unit factors from an already computed Smith-factor list.
-/
public noncomputable def displayFactors
    {R : Type _} [MonoidWithZero R]
    (factors : List R) : List R := by
  classical
  exact factors.filter fun factor => ¬ IsUnit factor

/--
Human-facing invariant factors.  Unit factors are omitted because their
cyclic quotients are zero; the theorem-facing decomposition keeps them.
-/
public noncomputable def displayInvariantFactors
    {R : Type _}
    [EuclideanDomain R] [NormalizationMonoid R]
    [ComputableEuclideanOps R] [DecidableEq R]
    [Matrix.Hermite.CanonicalMod R]
    (presentation : FiniteFreePresentation R) : List R := by
  exact displayFactors presentation.invariantFactors

@[simp] public theorem mem_displayFactors
    {R : Type _} [MonoidWithZero R]
    (factors : List R) (factor : R) :
    factor ∈ displayFactors factors ↔
      factor ∈ factors ∧ ¬ IsUnit factor := by
  classical
  simp [displayFactors]

@[simp] public theorem mem_displayInvariantFactors
    {R : Type _}
    [EuclideanDomain R] [NormalizationMonoid R]
    [ComputableEuclideanOps R] [DecidableEq R]
    [Matrix.Hermite.CanonicalMod R]
    (presentation : FiniteFreePresentation R) (factor : R) :
    factor ∈ presentation.displayInvariantFactors ↔
      factor ∈ presentation.invariantFactors ∧ ¬ IsUnit factor := by
  simp [displayInvariantFactors]

/--
Smith decomposition of the presented module.

Every nonzero diagonal factor appears, including units.  Consequently the
corresponding zero quotient modules remain present in this theorem-facing
equivalence.
-/
public noncomputable def smithDecomposition
    {R : Type _}
    [EuclideanDomain R] [NormalizationMonoid R]
    [ComputableEuclideanOps R] [DecidableEq R]
    [Matrix.Hermite.CanonicalMod R]
    (presentation : FiniteFreePresentation R) :
    presentation.presentedModule ≃ₗ[R]
      (((i : Fin presentation.smithRank) →
          R ⧸ Ideal.span ({presentation.invariantFactor i} : Set R)) ×
        (Fin presentation.freeRank → R)) := by
  simpa [presentedModule, relationSubmodule, relationMap, smithRank,
    invariantFactor, freeRank, pidSmithColumnSpan, smithColumnSpan,
    Fintype.card_fin] using
    pidExecutableQuotientEquivPiSpanProd presentation.relationMatrix

end FiniteFreePresentation

end NormalForms
