/-
Copyright (c) 2026 Junye Ji. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Junye Ji
-/
module

public import NormalForms.Presentation.Basic

/-!
# Fitting Ideals of a Finite-Free Presentation

For a column-oriented map `R^relations → R^generators`, the `k`th Fitting
ideal is generated by the `(numGenerators - k)` minors.  This is a semantic
definition at the presentation layer; the executable normal-form algorithm
does not enumerate minors.
-/

@[expose] public section

namespace NormalForms

namespace FiniteFreePresentation

/-- The `k`th Fitting ideal of the presented module. -/
public def fittingIdeal
    {R : Type _} [CommRing R]
    (presentation : FiniteFreePresentation R) (k : Nat) :
    Ideal R :=
  Matrix.Smith.determinantalIdealFin presentation.relationMatrix
    (presentation.numGenerators - k)

/-- Once `k` reaches the number of generators, the Fitting ideal is the unit ideal. -/
@[simp] public theorem fittingIdeal_eq_top_of_numGenerators_le
    {R : Type _} [CommRing R]
    (presentation : FiniteFreePresentation R) (k : Nat)
    (hk : presentation.numGenerators ≤ k) :
    presentation.fittingIdeal k = ⊤ := by
  rw [fittingIdeal, Nat.sub_eq_zero_of_le hk]
  exact Matrix.Smith.determinantalIdealFin_zero _

@[simp] public theorem fittingIdeal_numGenerators
    {R : Type _} [CommRing R]
    (presentation : FiniteFreePresentation R) :
    presentation.fittingIdeal presentation.numGenerators = ⊤ :=
  presentation.fittingIdeal_eq_top_of_numGenerators_le
    presentation.numGenerators (Nat.le_refl _)

/-- An oversized requested minor makes the corresponding Fitting ideal zero. -/
public theorem fittingIdeal_eq_bot_of_min_lt
    {R : Type _} [CommRing R]
    (presentation : FiniteFreePresentation R) (k : Nat)
    (hminor :
      Nat.min presentation.numGenerators presentation.numRelations <
        presentation.numGenerators - k) :
    presentation.fittingIdeal k = ⊥ :=
  Matrix.Smith.determinantalIdealFin_eq_bot_of_min_lt
    presentation.relationMatrix hminor

end FiniteFreePresentation

end NormalForms
