/-
Copyright (c) 2026 Junye Ji. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Junye Ji
-/
module

public import NormalForms.Matrix.Smith.Signature
import all NormalForms.Matrix.Smith.Signature

/-!
# Determinantal Ideals

The `k`th determinantal ideal is generated by all `k × k` minors.  This file
is proof infrastructure, not an executable minors-enumeration algorithm.  It
characterizes the ideal of a canonical Smith matrix by the product of its
first `k` diagonal entries and proves invariance under explicit two-sided
inverse certificates and finite reindexing.
-/

namespace NormalForms.Matrix.Smith

open NormalForms.Matrix
open NormalForms.Matrix.Certificates

/-- Determinants of all `k × k` minors of a canonical `Fin` matrix. -/
@[expose] public def minorDeterminantsFin {m n : Nat} {R : Type _}
    [CommRing R] (A : _root_.Matrix (Fin m) (Fin n) R) (k : Nat) :
    Set R :=
  Set.range fun embeddings :
      (Fin k ↪ Fin m) × (Fin k ↪ Fin n) =>
    _root_.Matrix.det
      (A.submatrix embeddings.1 embeddings.2)

/-- The ideal generated by all `k × k` minors. -/
@[expose] public def determinantalIdealFin {m n : Nat} {R : Type _}
    [CommRing R] (A : _root_.Matrix (Fin m) (Fin n) R) (k : Nat) :
    Ideal R :=
  Ideal.span (minorDeterminantsFin A k)

/-- Determinantal ideals relative to an explicitly stored finite indexing. -/
@[expose] public def determinantalIdealWith {m n R : Type _}
    [Fintype m] [Fintype n] [CommRing R]
    (indexing : MatrixIndexing m n) (A : _root_.Matrix m n R) (k : Nat) :
    Ideal R :=
  determinantalIdealFin (indexing.reindex A) k

namespace SmithData

/-- Product of the first `k` entries in the nonzero diagonal prefix. -/
@[expose] public def prefixProduct {m n : Nat} {R : Type _}
    [EuclideanDomain R] [NormalizationMonoid R]
    (data : SmithData m n R) (k : Nat) (hk : k ≤ data.rank) :
    R :=
  ∏ i : Fin k,
    data.diagonal
      (Fin.castLE (Nat.le_trans hk data.rank_le) i)

@[simp] public theorem prefixProduct_zero {m n : Nat} {R : Type _}
    [EuclideanDomain R] [NormalizationMonoid R]
    (data : SmithData m n R) :
    data.prefixProduct 0 (Nat.zero_le data.rank) = 1 := by
  simp [prefixProduct]

/-- A prefix inside the exact Smith rank has nonzero product. -/
public theorem prefixProduct_ne_zero {m n : Nat} {R : Type _}
    [EuclideanDomain R] [NormalizationMonoid R]
    (data : SmithData m n R) (k : Nat) (hk : k ≤ data.rank) :
    data.prefixProduct k hk ≠ 0 := by
  rw [prefixProduct, Finset.prod_ne_zero_iff]
  intro i _
  exact data.nonzero_prefix
    (Fin.castLE (Nat.le_trans hk data.rank_le) i)
    (Nat.lt_of_lt_of_le i.is_lt hk)

/-- Extending a prefix appends the next canonical diagonal entry. -/
public theorem prefixProduct_succ {m n : Nat} {R : Type _}
    [EuclideanDomain R] [NormalizationMonoid R]
    (data : SmithData m n R) (k : Nat) (hk : k + 1 ≤ data.rank) :
    data.prefixProduct (k + 1) hk =
      data.prefixProduct k (Nat.le_trans (Nat.le_succ k) hk) *
        data.diagonal
          (Fin.castLE data.rank_le
            ⟨k, Nat.lt_of_lt_of_le (Nat.lt_succ_self k) hk⟩) := by
  classical
  rw [prefixProduct, prefixProduct, Fin.prod_univ_castSucc]
  congr 1

end SmithData

/-- Transposition merely swaps the row and column embeddings of every minor. -/
public theorem minorDeterminantsFin_transpose {m n k : Nat} {R : Type _}
    [CommRing R] (A : _root_.Matrix (Fin m) (Fin n) R) :
    minorDeterminantsFin A.transpose k = minorDeterminantsFin A k := by
  ext x
  constructor
  · rintro ⟨⟨r, c⟩, rfl⟩
    refine ⟨⟨c, r⟩, ?_⟩
    simpa [_root_.Matrix.transpose_submatrix] using
      (_root_.Matrix.det_transpose (M := A.submatrix c r)).symm
  · rintro ⟨⟨r, c⟩, rfl⟩
    refine ⟨⟨c, r⟩, ?_⟩
    simpa [_root_.Matrix.transpose_submatrix] using
      (_root_.Matrix.det_transpose (M := A.submatrix r c))

/-- Determinantal ideals are invariant under matrix transposition. -/
public theorem determinantalIdealFin_transpose {m n : Nat} {R : Type _}
    [CommRing R] (A : _root_.Matrix (Fin m) (Fin n) R) (k : Nat) :
    determinantalIdealFin A.transpose k = determinantalIdealFin A k := by
  rw [determinantalIdealFin, determinantalIdealFin,
    minorDeterminantsFin_transpose]

/--
Right multiplication can only decrease a determinantal ideal.  This is the
Cauchy--Binet direction needed for certified two-sided invariance.
-/
public theorem determinantalIdealFin_mul_right_le
    {k m n p : Nat} {R : Type _} [CommRing R]
    (M : _root_.Matrix (Fin m) (Fin n) R)
    (N : _root_.Matrix (Fin n) (Fin p) R) :
    determinantalIdealFin (M * N) k ≤ determinantalIdealFin M k := by
  rw [determinantalIdealFin]
  refine Ideal.span_le.mpr ?_
  rintro x ⟨⟨r, c⟩, rfl⟩
  change
    _root_.Matrix.det ((M * N).submatrix r c) ∈
      determinantalIdealFin M k
  rw [Internal.det_submatrix_mul_sum_embeddings M N r c]
  apply Ideal.sum_mem
  intro e he
  exact
    (determinantalIdealFin M k).mul_mem_right
      (∏ i, N (e i) (c i))
      (Ideal.subset_span ⟨⟨r, e⟩, rfl⟩)

/-- Left multiplication can only decrease a determinantal ideal. -/
public theorem determinantalIdealFin_mul_left_le
    {k m n : Nat} {R : Type _} [CommRing R]
    (U : _root_.Matrix (Fin m) (Fin m) R)
    (M : _root_.Matrix (Fin m) (Fin n) R) :
    determinantalIdealFin (U * M) k ≤ determinantalIdealFin M k := by
  calc
    determinantalIdealFin (U * M) k =
        determinantalIdealFin (U * M).transpose k :=
      (determinantalIdealFin_transpose (U * M) k).symm
    _ = determinantalIdealFin (M.transpose * U.transpose) k := by
      rw [_root_.Matrix.transpose_mul]
    _ ≤ determinantalIdealFin M.transpose k :=
      determinantalIdealFin_mul_right_le M.transpose U.transpose
    _ = determinantalIdealFin M k :=
      determinantalIdealFin_transpose M k

/--
An explicit two-sided inverse certificate preserves every determinantal
ideal.  No determinant inverse or choice-based matrix inverse is recovered.
-/
public theorem determinantalIdealFin_eq_of_certificate
    {m n : Nat} {R : Type _} [CommRing R]
    {A : _root_.Matrix (Fin m) (Fin n) R}
    (certificate : TwoSidedCertificate A) (k : Nat) :
    determinantalIdealFin A k =
      determinantalIdealFin certificate.result k := by
  have hResultLe :
      determinantalIdealFin certificate.result k ≤
        determinantalIdealFin A k := by
    rw [← certificate.equation]
    exact
      le_trans
        (determinantalIdealFin_mul_right_le
          (certificate.U * A) certificate.V)
        (determinantalIdealFin_mul_left_le certificate.U A)
  have hRecover :
      certificate.U_cert.inverse * certificate.result *
          certificate.V_cert.inverse = A := by
    calc
      certificate.U_cert.inverse * certificate.result *
            certificate.V_cert.inverse =
          certificate.U_cert.inverse *
              (certificate.U * A * certificate.V) *
            certificate.V_cert.inverse := by
              rw [certificate.equation]
      _ = (certificate.U_cert.inverse * certificate.U) * A *
            (certificate.V * certificate.V_cert.inverse) := by
              simp only [_root_.Matrix.mul_assoc]
      _ = A := by
        rw [certificate.U_cert.left_inv, certificate.V_cert.right_inv]
        simp
  have hSourceLe :
      determinantalIdealFin A k ≤
        determinantalIdealFin certificate.result k := by
    calc
      determinantalIdealFin A k =
          determinantalIdealFin
            (certificate.U_cert.inverse * certificate.result *
              certificate.V_cert.inverse) k :=
        congrArg (fun M => determinantalIdealFin M k) hRecover.symm
      _ ≤ determinantalIdealFin certificate.result k :=
        le_trans
          (determinantalIdealFin_mul_right_le
            (certificate.U_cert.inverse * certificate.result)
            certificate.V_cert.inverse)
          (determinantalIdealFin_mul_left_le
            certificate.U_cert.inverse certificate.result)
  exact le_antisymm hSourceLe hResultLe

/-- The zeroth determinantal ideal is the unit ideal. -/
@[simp] public theorem determinantalIdealFin_zero
    {m n : Nat} {R : Type _} [CommRing R]
    (A : _root_.Matrix (Fin m) (Fin n) R) :
    determinantalIdealFin A 0 = ⊤ := by
  apply (Ideal.eq_top_iff_one _).mpr
  apply Ideal.subset_span
  refine
    ⟨⟨Internal.initialEmbedding (Nat.zero_le m),
        Internal.initialEmbedding (Nat.zero_le n)⟩, ?_⟩
  simp

/-- There are no `k × k` minors once `k` exceeds either matrix dimension. -/
public theorem determinantalIdealFin_eq_bot_of_min_lt
    {m n k : Nat} {R : Type _} [CommRing R]
    (A : _root_.Matrix (Fin m) (Fin n) R)
    (hmin : Nat.min m n < k) :
    determinantalIdealFin A k = ⊥ := by
  apply le_antisymm
  · rw [determinantalIdealFin]
    refine Ideal.span_le.mpr ?_
    rintro x ⟨⟨r, c⟩, hx⟩
    have hr : k ≤ m := by
      simpa using Fintype.card_le_of_injective r r.injective
    have hc : k ≤ n := by
      simpa using Fintype.card_le_of_injective c c.injective
    exact
      (Nat.not_le_of_gt hmin
        (le_min_iff.mpr ⟨hr, hc⟩)).elim
  · exact bot_le

/--
For `k` inside the nonzero prefix, the `k`th determinantal ideal is generated
by the product of the first `k` canonical diagonal entries.
-/
public theorem determinantalIdealFin_eq_span_prefixProduct
    {m n : Nat} {R : Type _}
    [EuclideanDomain R] [NormalizationMonoid R] [DecidableEq R]
    {A : _root_.Matrix (Fin m) (Fin n) R}
    (hA : IsSmithNormalFormFin A)
    (k : Nat)
    (hk : k ≤ (SmithData.ofSmithMatrix A hA).rank) :
    determinantalIdealFin A k =
      Ideal.span
        {(SmithData.ofSmithMatrix A hA).prefixProduct k hk} := by
  let data := SmithData.ofSmithMatrix A hA
  let hdim : k ≤ Nat.min m n := Nat.le_trans hk data.rank_le
  have hprefix :
      data.prefixProduct k hk =
        Internal.diagPrefixProduct A k hdim := by
    rfl
  rcases Internal.isSmithNormalFormFin_toDiag hA with
    ⟨hOff, _, hChain⟩
  apply le_antisymm
  · rw [determinantalIdealFin]
    refine Ideal.span_le.mpr ?_
    rintro x ⟨⟨r, c⟩, rfl⟩
    change
      _root_.Matrix.det (A.submatrix r c) ∈
        Ideal.span {data.prefixProduct k hk}
    rw [Ideal.mem_span_singleton, hprefix]
    exact
      Internal.diagPrefixProduct_dvd_minor
        hOff hChain hdim r c
  · refine Ideal.span_le.mpr ?_
    intro x hx
    rw [Set.mem_singleton_iff] at hx
    subst x
    apply Ideal.subset_span
    refine
      ⟨⟨Internal.initialEmbedding
            (Nat.le_trans hdim (Nat.min_le_left m n)),
          Internal.initialEmbedding
            (Nat.le_trans hdim (Nat.min_le_right m n))⟩, ?_⟩
    exact
      (Internal.det_leadingMinor_eq_diagPrefixProduct
        hOff hdim).trans hprefix.symm

/-- Minors beyond the Smith rank generate the zero ideal. -/
public theorem determinantalIdealFin_eq_bot_of_rank_lt
    {m n : Nat} {R : Type _}
    [EuclideanDomain R] [NormalizationMonoid R] [DecidableEq R]
    {A : _root_.Matrix (Fin m) (Fin n) R}
    (hA : IsSmithNormalFormFin A)
    (k : Nat)
    (hrank : (SmithData.ofSmithMatrix A hA).rank < k) :
    determinantalIdealFin A k = ⊥ := by
  by_cases hdim : k ≤ Nat.min m n
  · have hrank' :
        (Internal.invariantFactors A).length < k := by
      exact hrank
    have hzero :
        Internal.diagPrefixProduct A k hdim = 0 :=
      Internal.diagPrefixProduct_eq_zero_of_invariantFactors_length_lt
        hA k hrank' hdim
    rcases Internal.isSmithNormalFormFin_toDiag hA with
      ⟨hOff, _, hChain⟩
    apply le_antisymm
    · rw [determinantalIdealFin]
      refine Ideal.span_le.mpr ?_
      rintro x ⟨⟨r, c⟩, rfl⟩
      apply Ideal.mem_bot.mpr
      have hdiv :
          Internal.diagPrefixProduct A k hdim ∣
            _root_.Matrix.det (A.submatrix r c) :=
        Internal.diagPrefixProduct_dvd_minor
          hOff hChain hdim r c
      rw [hzero] at hdiv
      simpa using hdiv
    · exact bot_le
  · exact
      determinantalIdealFin_eq_bot_of_min_lt A
        (Nat.lt_of_not_ge hdim)

/--
Equal determinantal ideals recover the same nonzero Smith rank, even when the
two canonical matrices have different rectangular dimensions.
-/
public theorem smithRank_eq_of_determinantalIdeals
    {mA nA mB nB : Nat} {R : Type _}
    [EuclideanDomain R] [NormalizationMonoid R] [DecidableEq R]
    {A : _root_.Matrix (Fin mA) (Fin nA) R}
    {B : _root_.Matrix (Fin mB) (Fin nB) R}
    (hA : IsSmithNormalFormFin A)
    (hB : IsSmithNormalFormFin B)
    (hdet : ∀ k, determinantalIdealFin A k = determinantalIdealFin B k) :
    (SmithData.ofSmithMatrix A hA).rank =
      (SmithData.ofSmithMatrix B hB).rank := by
  let dataA := SmithData.ofSmithMatrix A hA
  let dataB := SmithData.ofSmithMatrix B hB
  apply Nat.le_antisymm
  · by_contra hle
    have hlt : dataB.rank < dataA.rank := Nat.lt_of_not_ge hle
    let k := dataB.rank + 1
    have hkA : k ≤ dataA.rank := hlt
    have hspanbot :
        Ideal.span ({dataA.prefixProduct k hkA} : Set R) = ⊥ := by
      calc
        Ideal.span ({dataA.prefixProduct k hkA} : Set R) =
            determinantalIdealFin A k :=
          (determinantalIdealFin_eq_span_prefixProduct hA k hkA).symm
        _ = determinantalIdealFin B k := hdet k
        _ = ⊥ :=
          determinantalIdealFin_eq_bot_of_rank_lt hB k
            (Nat.lt_succ_self dataB.rank)
    exact dataA.prefixProduct_ne_zero k hkA
      (Ideal.span_singleton_eq_bot.mp hspanbot)
  · by_contra hle
    have hlt : dataA.rank < dataB.rank := Nat.lt_of_not_ge hle
    let k := dataA.rank + 1
    have hkB : k ≤ dataB.rank := hlt
    have hspanbot :
        Ideal.span ({dataB.prefixProduct k hkB} : Set R) = ⊥ := by
      calc
        Ideal.span ({dataB.prefixProduct k hkB} : Set R) =
            determinantalIdealFin B k :=
          (determinantalIdealFin_eq_span_prefixProduct hB k hkB).symm
        _ = determinantalIdealFin A k := (hdet k).symm
        _ = ⊥ :=
          determinantalIdealFin_eq_bot_of_rank_lt hA k
            (Nat.lt_succ_self dataA.rank)
    exact dataB.prefixProduct_ne_zero k hkB
      (Ideal.span_singleton_eq_bot.mp hspanbot)

/--
Equal determinantal ideals recover the same multiset of nonzero associate
factors, independently of the matrices' zero-tail dimensions.
-/
public theorem smithFactors_eq_of_determinantalIdeals
    {mA nA mB nB : Nat} {R : Type _}
    [EuclideanDomain R] [NormalizationMonoid R] [DecidableEq R]
    {A : _root_.Matrix (Fin mA) (Fin nA) R}
    {B : _root_.Matrix (Fin mB) (Fin nB) R}
    (hA : IsSmithNormalFormFin A)
    (hB : IsSmithNormalFormFin B)
    (hdet : ∀ k, determinantalIdealFin A k = determinantalIdealFin B k) :
    (SmithData.ofSmithMatrix A hA).signature.factors =
      (SmithData.ofSmithMatrix B hB).signature.factors := by
  let dataA := SmithData.ofSmithMatrix A hA
  let dataB := SmithData.ofSmithMatrix B hB
  have hrank : dataA.rank = dataB.rank :=
    smithRank_eq_of_determinantalIdeals hA hB hdet
  change
    Multiset.ofList (List.ofFn dataA.factorAt) =
      Multiset.ofList (List.ofFn dataB.factorAt)
  apply congrArg Multiset.ofList
  apply List.ext_get
  · simp [hrank]
  · intro q hqA hqB
    simp only [List.length_ofFn] at hqA hqB
    rw [List.get_ofFn, List.get_ofFn]
    have hprefix :
        ∀ k (hkA : k ≤ dataA.rank) (hkB : k ≤ dataB.rank),
          Associates.mk (dataA.prefixProduct k hkA) =
            Associates.mk (dataB.prefixProduct k hkB) := by
      intro k hkA hkB
      apply Associates.mk_eq_mk_iff_associated.mpr
      apply Ideal.span_singleton_eq_span_singleton.mp
      calc
        Ideal.span ({dataA.prefixProduct k hkA} : Set R) =
            determinantalIdealFin A k :=
          (determinantalIdealFin_eq_span_prefixProduct hA k hkA).symm
        _ = determinantalIdealFin B k := hdet k
        _ = Ideal.span ({dataB.prefixProduct k hkB} : Set R) :=
          determinantalIdealFin_eq_span_prefixProduct hB k hkB
    have hkA : q ≤ dataA.rank := Nat.le_of_lt hqA
    have hkB : q ≤ dataB.rank := Nat.le_of_lt hqB
    have hksuccA : q + 1 ≤ dataA.rank := hqA
    have hksuccB : q + 1 ≤ dataB.rank := hqB
    have hprod := hprefix (q + 1) hksuccA hksuccB
    rw [dataA.prefixProduct_succ q hksuccA,
      dataB.prefixProduct_succ q hksuccB,
      ← Associates.mk_mul_mk, ← Associates.mk_mul_mk,
      hprefix q hkA hkB] at hprod
    have hfactor :=
      mul_left_cancel₀
        (by
          rw [Associates.mk_ne_zero]
          exact dataB.prefixProduct_ne_zero q hkB)
        hprod
    simpa [SmithData.factorAt] using hfactor

/--
The full family of determinantal ideals determines the ordered normalized
Smith data.  The proof first recovers the exact rank from the first zero
ideal, then cancels consecutive nonzero prefix products in `Associates R`.
-/
public theorem smithData_eq_of_determinantalIdeals
    {m n : Nat} {R : Type _}
    [EuclideanDomain R] [NormalizationMonoid R] [DecidableEq R]
    {A B : _root_.Matrix (Fin m) (Fin n) R}
    (hA : IsSmithNormalFormFin A)
    (hB : IsSmithNormalFormFin B)
    (hdet : ∀ k, determinantalIdealFin A k = determinantalIdealFin B k) :
    SmithData.ofSmithMatrix A hA =
      SmithData.ofSmithMatrix B hB := by
  let dataA := SmithData.ofSmithMatrix A hA
  let dataB := SmithData.ofSmithMatrix B hB
  have hrank : dataA.rank = dataB.rank :=
    smithRank_eq_of_determinantalIdeals hA hB hdet
  apply SmithData.ext hrank
  funext i
  by_cases hiA : i.1 < dataA.rank
  · have hiB : i.1 < dataB.rank := by
      rwa [← hrank]
    have hprefix :
        ∀ k (hkA : k ≤ dataA.rank) (hkB : k ≤ dataB.rank),
          Associates.mk (dataA.prefixProduct k hkA) =
            Associates.mk (dataB.prefixProduct k hkB) := by
      intro k hkA hkB
      apply Associates.mk_eq_mk_iff_associated.mpr
      apply Ideal.span_singleton_eq_span_singleton.mp
      calc
        Ideal.span ({dataA.prefixProduct k hkA} : Set R) =
            determinantalIdealFin A k :=
          (determinantalIdealFin_eq_span_prefixProduct hA k hkA).symm
        _ = determinantalIdealFin B k := hdet k
        _ = Ideal.span ({dataB.prefixProduct k hkB} : Set R) :=
          determinantalIdealFin_eq_span_prefixProduct hB k hkB
    have hkA : i.1 ≤ dataA.rank := Nat.le_of_lt hiA
    have hkB : i.1 ≤ dataB.rank := Nat.le_of_lt hiB
    have hksuccA : i.1 + 1 ≤ dataA.rank := hiA
    have hksuccB : i.1 + 1 ≤ dataB.rank := hiB
    have hprod := hprefix (i.1 + 1) hksuccA hksuccB
    rw [dataA.prefixProduct_succ i.1 hksuccA,
      dataB.prefixProduct_succ i.1 hksuccB,
      ← Associates.mk_mul_mk, ← Associates.mk_mul_mk,
      hprefix i.1 hkA hkB] at hprod
    have hfactor :=
      mul_left_cancel₀
        (by
          rw [Associates.mk_ne_zero]
          exact dataB.prefixProduct_ne_zero i.1 hkB)
        hprod
    apply Associated.eq_of_normalized
      (Associates.mk_eq_mk_iff_associated.mp (by simpa using hfactor))
    · exact (dataA.normalized i).symm
    · exact (dataB.normalized i).symm
  · have hiAge : dataA.rank ≤ i.1 := Nat.le_of_not_gt hiA
    have hiBge : dataB.rank ≤ i.1 := by
      rwa [← hrank]
    rw [dataA.zero_tail i hiAge, dataB.zero_tail i hiBge]

/-- Determinantal ideals therefore determine the intrinsic Smith signature. -/
public theorem smithSignature_eq_of_determinantalIdeals
    {m n : Nat} {R : Type _}
    [EuclideanDomain R] [NormalizationMonoid R] [DecidableEq R]
    {A B : _root_.Matrix (Fin m) (Fin n) R}
    (hA : IsSmithNormalFormFin A)
    (hB : IsSmithNormalFormFin B)
    (hdet : ∀ k, determinantalIdealFin A k = determinantalIdealFin B k) :
    (SmithData.ofSmithMatrix A hA).signature =
      (SmithData.ofSmithMatrix B hB).signature :=
  congrArg SmithData.signature
    (smithData_eq_of_determinantalIdeals hA hB hdet)

/-- Explicit row/column re-enumeration preserves every determinantal ideal. -/
public theorem determinantalIdealWith_eq_of_indexing_change
    {m n R : Type _}
    [Fintype m] [Fintype n] [CommRing R]
    (source target : MatrixIndexing m n)
    (A : _root_.Matrix m n R) (k : Nat) :
    determinantalIdealWith source A k =
      determinantalIdealWith target A k := by
  classical
  let certificate : TwoSidedCertificate (source.reindex A) :=
    { U := source.rowPermutation (R := R) target
      U_cert := MatrixInverseCertificate.rowPermutation source target
      result := target.reindex A
      V := source.columnPermutation (R := R) target
      V_cert := MatrixInverseCertificate.columnPermutation source target
      equation :=
        MatrixIndexing.rowPermutation_mul_reindex_mul_columnPermutation
          source target A }
  exact determinantalIdealFin_eq_of_certificate certificate k

end NormalForms.Matrix.Smith
