/-
Copyright (c) 2026 Junye Ji. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Junye Ji
-/
module

public import NormalForms.Research.ModularHNF.Algorithm
public import NormalForms.Matrix.Hermite.Bezout
import all NormalForms.Research.ModularHNF.Algorithm
import all NormalForms.Matrix.Hermite.Bezout
import Mathlib.Algebra.BigOperators.Pi

/-!
# Row-lattice infrastructure for modular HNF

The modular kernel is proved against the integer submodule generated by its
rows.  During column `k`, multiples of the coordinate vectors `R e_j` for
`j >= k` are explicit auxiliary generators.  Centered reduction therefore
changes representatives, not the augmented lattice.
-/

public section

namespace NormalForms.Research.ModularHNF

open scoped BigOperators Matrix
open NormalForms
open NormalForms.Matrix.Certificates
open NormalForms.Matrix.Hermite

/-- Integer submodule generated by the rows of a matrix. -/
@[expose] public def rowSpan {m n : Nat}
    (A : _root_.Matrix (Fin m) (Fin n) Int) :
    Submodule Int (Fin n → Int) :=
  Submodule.span Int (Set.range A.row)

/-- Remaining coordinates represented by the modular auxiliary basis. -/
public abbrev SuffixIndex (n k : Nat) :=
  { column : Fin n // k ≤ column.val }

/-- Span of `R e_j` over the not-yet-processed suffix. -/
@[expose] public def suffixModule {n : Nat} (modulus : Int) (k : Nat) :
    Submodule Int (Fin n → Int) :=
  Submodule.span Int <| Set.range fun column : SuffixIndex n k =>
    modulus • Pi.single column.1 (1 : Int)

/-- Rows together with the live modular suffix generators. -/
@[expose] public def augmentedRowSpan {m n : Nat}
    (A : _root_.Matrix (Fin m) (Fin n) Int)
    (modulus : Int) (k : Nat) : Submodule Int (Fin n → Int) :=
  rowSpan A ⊔ suffixModule modulus k

public theorem row_mem_rowSpan {m n : Nat}
    (A : _root_.Matrix (Fin m) (Fin n) Int) (row : Fin m) :
    A.row row ∈ rowSpan A :=
  Submodule.subset_span (Set.mem_range_self row)

public theorem suffixGenerator_mem {n k : Nat} (modulus : Int)
    (column : SuffixIndex n k) :
    modulus • Pi.single column.1 (1 : Int) ∈ suffixModule modulus k :=
  Submodule.subset_span (Set.mem_range_self column)

theorem row_mul_mem_rowSpan {m n : Nat}
    (U : _root_.Matrix (Fin m) (Fin m) Int)
    (A : _root_.Matrix (Fin m) (Fin n) Int) (row : Fin m) :
    (U * A).row row ∈ rowSpan A := by
  have hsum :
      (U * A).row row = ∑ middle : Fin m, U row middle • A.row middle := by
    ext column
    simp [_root_.Matrix.mul_apply]
  rw [hsum]
  exact Submodule.sum_mem _ fun middle _ =>
    Submodule.smul_mem _ _ (row_mem_rowSpan A middle)

public theorem rowSpan_mul_le {m n : Nat}
    (U : _root_.Matrix (Fin m) (Fin m) Int)
    (A : _root_.Matrix (Fin m) (Fin n) Int) :
    rowSpan (U * A) ≤ rowSpan A := by
  rw [rowSpan, Submodule.span_le]
  rintro _ ⟨row, rfl⟩
  exact row_mul_mem_rowSpan U A row

/-- Certified left multiplication preserves the generated integer row lattice. -/
public theorem rowSpan_mul_eq {m n : Nat}
    {U : _root_.Matrix (Fin m) (Fin m) Int}
    (certificate : MatrixInverseCertificate U)
    (A : _root_.Matrix (Fin m) (Fin n) Int) :
    rowSpan (U * A) = rowSpan A := by
  apply le_antisymm (rowSpan_mul_le U A)
  have reverse := rowSpan_mul_le certificate.inverse (U * A)
  have matrixEq : certificate.inverse * (U * A) = A := by
    rw [← _root_.Matrix.mul_assoc, certificate.left_inv]
    simp
  simpa [matrixEq] using reverse

/-- Coordinate criterion for membership in the live modular suffix. -/
public theorem mem_suffixModule_of_coordinates {n k : Nat}
    {modulus : Int} {vector : Fin n → Int}
    (zeroBefore : ∀ column, column.val < k → vector column = 0)
    (divisibleAfter : ∀ column, k ≤ column.val → modulus ∣ vector column) :
    vector ∈ suffixModule modulus k := by
  rw [pi_eq_sum_univ' vector]
  apply Submodule.sum_mem
  intro column _
  by_cases after : k ≤ column.val
  · rcases divisibleAfter column after with ⟨coefficient, equality⟩
    rw [equality]
    have generator := suffixGenerator_mem modulus
      (⟨column, after⟩ : SuffixIndex n k)
    convert Submodule.smul_mem (suffixModule modulus k) coefficient generator using 1
    simp [mul_comm, mul_assoc]
  · have before : column.val < k := Nat.lt_of_not_ge after
    rw [zeroBefore column before]
    simp

/-- Membership in the suffix span forces a zero prefix and coordinatewise divisibility. -/
public theorem suffixModule_coordinates {n k : Nat}
    {modulus : Int} {vector : Fin n → Int}
    (membership : vector ∈ suffixModule modulus k) :
    (∀ column, column.val < k → vector column = 0) ∧
      (∀ column, modulus ∣ vector column) := by
  rcases (Submodule.mem_span_range_iff_exists_fun Int).mp membership with
    ⟨coeff, equality⟩
  constructor
  · intro column before
    have entry := congrFun equality column
    rw [← entry]
    simp only [Finset.sum_apply]
    apply Finset.sum_eq_zero
    intro source _
    have sourceNe : source.1 ≠ column := by
      intro equal
      subst equal
      omega
    simp [sourceNe]
  · intro column
    have entry := congrFun equality column
    rw [← entry]
    simp only [Finset.sum_apply]
    apply Finset.dvd_sum
    intro source _
    let entry : Int :=
      (Pi.single source.1 (1 : Int) : Fin n → Int) column
    refine ⟨coeff source * entry, ?_⟩
    change coeff source * (modulus * entry) =
      modulus * (coeff source * entry)
    ring

/-- Rowwise congruence modulo the suffix auxiliary basis. -/
@[expose] public def RowsCongruentOnSuffix {m n : Nat}
    (left right : _root_.Matrix (Fin m) (Fin n) Int)
    (modulus : Int) (k : Nat) : Prop :=
  ∀ row, left.row row - right.row row ∈ suffixModule modulus k

namespace RowsCongruentOnSuffix

public theorem refl {m n : Nat}
    (A : _root_.Matrix (Fin m) (Fin n) Int) (modulus : Int) (k : Nat) :
    RowsCongruentOnSuffix A A modulus k := by
  intro row
  simp

public theorem symm {m n : Nat}
    {left right : _root_.Matrix (Fin m) (Fin n) Int}
    {modulus : Int} {k : Nat}
    (congruent : RowsCongruentOnSuffix left right modulus k) :
    RowsCongruentOnSuffix right left modulus k := by
  intro row
  have equality :
      right.row row - left.row row = -(left.row row - right.row row) := by
    module
  rw [equality]
  exact Submodule.neg_mem _ (congruent row)

public theorem trans {m n : Nat}
    {first second third : _root_.Matrix (Fin m) (Fin n) Int}
    {modulus : Int} {k : Nat}
    (left : RowsCongruentOnSuffix first second modulus k)
    (right : RowsCongruentOnSuffix second third modulus k) :
    RowsCongruentOnSuffix first third modulus k := by
  intro row
  have equality :
      first.row row - third.row row =
        (first.row row - second.row row) +
          (second.row row - third.row row) := by
    module
  rw [equality]
  exact Submodule.add_mem _ (left row) (right row)

end RowsCongruentOnSuffix

theorem rowSpan_le_augmented_of_congruent {m n : Nat}
    {left right : _root_.Matrix (Fin m) (Fin n) Int}
    {modulus : Int} {k : Nat}
    (congruent : RowsCongruentOnSuffix left right modulus k) :
    rowSpan left ≤ augmentedRowSpan right modulus k := by
  rw [rowSpan, Submodule.span_le]
  rintro _ ⟨row, rfl⟩
  have rightMem : right.row row ∈ augmentedRowSpan right modulus k :=
    Submodule.mem_sup_left (row_mem_rowSpan right row)
  have differenceMem :
      left.row row - right.row row ∈ augmentedRowSpan right modulus k :=
    Submodule.mem_sup_right (congruent row)
  have equality :
      left.row row = right.row row + (left.row row - right.row row) := by
    module
  rw [equality]
  exact Submodule.add_mem _ rightMem differenceMem

/-- Suffix-congruent matrices generate the same augmented row lattice. -/
public theorem augmentedRowSpan_eq_of_congruent {m n : Nat}
    {left right : _root_.Matrix (Fin m) (Fin n) Int}
    {modulus : Int} {k : Nat}
    (congruent : RowsCongruentOnSuffix left right modulus k) :
    augmentedRowSpan left modulus k = augmentedRowSpan right modulus k := by
  apply le_antisymm
  · apply sup_le
    · exact rowSpan_le_augmented_of_congruent congruent
    · exact le_sup_right
  · apply sup_le
    · exact rowSpan_le_augmented_of_congruent congruent.symm
    · exact le_sup_right

/-- A suffix perturbation after an invertible row transform preserves the augmented lattice. -/
public theorem augmentedRowSpan_eq_of_transform_congruent {m n : Nat}
    {A result : _root_.Matrix (Fin m) (Fin n) Int}
    {U : _root_.Matrix (Fin m) (Fin m) Int}
    (certificate : MatrixInverseCertificate U)
    {modulus : Int} {k : Nat}
    (congruent : RowsCongruentOnSuffix result (U * A) modulus k) :
    augmentedRowSpan result modulus k = augmentedRowSpan A modulus k := by
  rw [augmentedRowSpan_eq_of_congruent congruent, augmentedRowSpan,
    rowSpan_mul_eq certificate A]
  rfl

public theorem centeredMod_eq_add_mul (value modulus : Int) :
    ∃ coefficient, Internal.centeredMod value modulus =
      value + coefficient * modulus := by
  unfold Internal.centeredMod
  by_cases centered : modulus / 2 < value % modulus
  · refine ⟨-(value / modulus) - 1, ?_⟩
    rw [if_pos centered]
    rw [EuclideanDomain.mod_eq_sub_mul_div]
    ring
  · refine ⟨-(value / modulus), ?_⟩
    rw [if_neg centered]
    rw [EuclideanDomain.mod_eq_sub_mul_div]
    ring

end NormalForms.Research.ModularHNF
